name: Test and build

on:
  push:
    branches:
      - master
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Docker Setup
      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # Step 5: Run tests
      - name: Run tests
        run: |
          flake8 --ignore=E501,F401 .

      # Step 6: Docker login
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Generate Docker tag
      - name: Generate Docker tag
        id: version
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 8: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ env.VERSION }} .

      # Step 9: Push Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ env.VERSION }}
